import { createContext, useCallback, useContext, useEffect, useState } from "react";

const languageKey = "healthsync-language";
const tamil = {
  Dashboard: "டாஷ்போர்டு", "Create Doctor": "மருத்துவரை உருவாக்கு", "Manage Doctors": "மருத்துவர்களை நிர்வகி", "Manage Workers": "பணியாளர்களை நிர்வகி", "Analytics & Reports": "பகுப்பாய்வு மற்றும் அறிக்கைகள்", "Audit Logs": "செயல்பாட்டுப் பதிவுகள்", Settings: "அமைப்புகள்", Profile: "சுயவிவரம்", Logout: "வெளியேறு", Administrator: "நிர்வாகி", "HealthSync Management System": "ஹெல்த்சிங் மேலாண்மை அமைப்பு",
  "Manage your account, preferences, and security.": "உங்கள் கணக்கு, விருப்பங்கள் மற்றும் பாதுகாப்பை நிர்வகிக்கவும்.", "Profile settings": "சுயவிவர அமைப்புகள்", Name: "பெயர்", Email: "மின்னஞ்சல்", "Phone number": "தொலைபேசி எண்", "Change password": "கடவுச்சொல்லை மாற்று", "Leave blank to keep current password": "தற்போதைய கடவுச்சொல்லை வைத்திருக்க காலியாக விடவும்", "Upload profile picture": "சுயவிவரப் படத்தைப் பதிவேற்று",
  "Account settings": "கணக்கு அமைப்புகள்", "Personal information is updated when you save this form.": "இந்த படிவத்தைச் சேமிக்கும்போது தனிப்பட்ட தகவல் புதுப்பிக்கப்படும்.", "Two-factor authentication": "இரு-காரணி அங்கீகாரம்", "Require an extra verification step when signing in.": "உள்நுழையும்போது கூடுதல் சரிபார்ப்பை கோரவும்.", "Notification settings": "அறிவிப்பு அமைப்புகள்", "Email notifications": "மின்னஞ்சல் அறிவிப்புகள்", "Push notifications": "புஷ் அறிவிப்புகள்", "SMS notifications": "SMS அறிவிப்புகள்",
  "Application settings": "பயன்பாட்டு அமைப்புகள்", Theme: "தீம்", Light: "வெளிர்", Dark: "இருள்", Language: "மொழி", English: "ஆங்கிலம்", Hindi: "இந்தி", Tamil: "தமிழ்", Malayalam: "மலையாளம்", "Time zone": "நேர மண்டலம்", "India Standard Time": "இந்திய நேரம்", "Eastern Time": "கிழக்கு நேரம்", "Security & privacy": "பாதுகாப்பு மற்றும் தனியுரிமை", "Active sessions:": "செயலில் உள்ள அமர்வுகள்:", "Enhanced privacy preferences": "மேம்படுத்தப்பட்ட தனியுரிமை விருப்பங்கள்", "Restrict optional data sharing and analytics.": "விருப்பத் தரவு பகிர்வு மற்றும் பகுப்பாய்வைக் கட்டுப்படுத்தவும்.", "Log out from all other devices": "மற்ற அனைத்து சாதனங்களிலிருந்தும் வெளியேறு", Saving: "சேமிக்கிறது…", "Save settings": "அமைப்புகளை சேமி",
  "Track all system activities.": "அனைத்து அமைப்பு செயல்பாடுகளையும் கண்காணிக்கவும்.", User: "பயனர்", Action: "செயல்", Date: "தேதி", Time: "நேரம்", "Loading live data…": "நேரடி தரவு ஏற்றப்படுகிறது…", "No audit activity is available.": "செயல்பாட்டுப் பதிவுகள் இல்லை."
};
const hindi = {
  Dashboard: "डैशबोर्ड", "Create Doctor": "डॉक्टर बनाएँ", "Manage Doctors": "डॉक्टर प्रबंधित करें", "Manage Workers": "कर्मचारी प्रबंधित करें", "Analytics & Reports": "विश्लेषण और रिपोर्ट", "Audit Logs": "ऑडिट लॉग", Settings: "सेटिंग्स", Profile: "प्रोफ़ाइल", Logout: "लॉग आउट", Administrator: "प्रशासक", "HealthSync Management System": "हेल्थसिंक प्रबंधन प्रणाली",
  "Manage your account, preferences, and security.": "अपना खाता, प्राथमिकताएँ और सुरक्षा प्रबंधित करें।", "Profile settings": "प्रोफ़ाइल सेटिंग्स", Name: "नाम", Email: "ईमेल", "Phone number": "फ़ोन नंबर", "Change password": "पासवर्ड बदलें", "Leave blank to keep current password": "वर्तमान पासवर्ड रखने के लिए खाली छोड़ें", "Upload profile picture": "प्रोफ़ाइल चित्र अपलोड करें",
  "Account settings": "खाता सेटिंग्स", "Personal information is updated when you save this form.": "इस फॉर्म को सहेजने पर व्यक्तिगत जानकारी अपडेट होगी।", "Two-factor authentication": "दो-कारक प्रमाणीकरण", "Require an extra verification step when signing in.": "साइन इन करते समय अतिरिक्त सत्यापन आवश्यक करें।", "Notification settings": "सूचना सेटिंग्स", "Email notifications": "ईमेल सूचनाएँ", "Push notifications": "पुश सूचनाएँ", "SMS notifications": "एसएमएस सूचनाएँ",
  "Application settings": "ऐप्लिकेशन सेटिंग्स", Theme: "थीम", Light: "लाइट", Dark: "डार्क", Language: "भाषा", English: "अंग्रेज़ी", Hindi: "हिंदी", Tamil: "तमिल", Malayalam: "मलयालम", "Time zone": "समय क्षेत्र", "India Standard Time": "भारतीय मानक समय", "Eastern Time": "पूर्वी समय", "Security & privacy": "सुरक्षा और गोपनीयता", "Active sessions:": "सक्रिय सत्र:", "Enhanced privacy preferences": "उन्नत गोपनीयता प्राथमिकताएँ", "Restrict optional data sharing and analytics.": "वैकल्पिक डेटा साझाकरण और विश्लेषण सीमित करें।", "Log out from all other devices": "अन्य सभी उपकरणों से लॉग आउट करें", Saving: "सहेजा जा रहा है…", "Save settings": "सेटिंग्स सहेजें",
  "Track all system activities.": "सभी सिस्टम गतिविधियों को ट्रैक करें।", User: "उपयोगकर्ता", Action: "कार्रवाई", Date: "तारीख", Time: "समय", "Loading live data…": "लाइव डेटा लोड हो रहा है…", "No audit activity is available.": "कोई ऑडिट गतिविधि उपलब्ध नहीं है।"
};
const malayalam = {
  Dashboard: "ഡാഷ്ബോർഡ്", "Create Doctor": "ഡോക്ടറെ സൃഷ്ടിക്കുക", "Manage Doctors": "ഡോക്ടർമാരെ നിയന്ത്രിക്കുക", "Manage Workers": "ജീവനക്കാരെ നിയന്ത്രിക്കുക", "Analytics & Reports": "വിശകലനവും റിപ്പോർട്ടുകളും", "Audit Logs": "ഓഡിറ്റ് രേഖകൾ", Settings: "ക്രമീകരണങ്ങൾ", Profile: "പ്രൊഫൈൽ", Logout: "ലോഗ് ഔട്ട്", Administrator: "അഡ്മിനിസ്ട്രേറ്റർ", "HealthSync Management System": "ഹെൽത്ത്‌സിങ്ക് മാനേജ്മെന്റ് സിസ്റ്റം",
  "Manage your account, preferences, and security.": "നിങ്ങളുടെ അക്കൗണ്ട്, മുൻഗണനകൾ, സുരക്ഷ എന്നിവ നിയന്ത്രിക്കുക.", "Profile settings": "പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ", Name: "പേര്", Email: "ഇമെയിൽ", "Phone number": "ഫോൺ നമ്പർ", "Change password": "പാസ്‌വേഡ് മാറ്റുക", "Leave blank to keep current password": "നിലവിലെ പാസ്‌വേഡ് നിലനിർത്താൻ ഒഴിവാക്കുക", "Upload profile picture": "പ്രൊഫൈൽ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
  "Account settings": "അക്കൗണ്ട് ക്രമീകരണങ്ങൾ", "Personal information is updated when you save this form.": "ഈ ഫോം സംരക്ഷിക്കുമ്പോൾ വ്യക്തിഗത വിവരങ്ങൾ അപ്ഡേറ്റ് ചെയ്യും.", "Two-factor authentication": "രണ്ട്-ഘട്ട ആധികാരികത", "Require an extra verification step when signing in.": "സൈൻ ഇൻ ചെയ്യുമ്പോൾ അധിക പരിശോധന ആവശ്യമാണ്.", "Notification settings": "അറിയിപ്പ് ക്രമീകരണങ്ങൾ", "Email notifications": "ഇമെയിൽ അറിയിപ്പുകൾ", "Push notifications": "പുഷ് അറിയിപ്പുകൾ", "SMS notifications": "SMS അറിയിപ്പുകൾ",
  "Application settings": "ആപ്ലിക്കേഷൻ ക്രമീകരണങ്ങൾ", Theme: "തീം", Light: "ലൈറ്റ്", Dark: "ഡാർക്ക്", Language: "ഭാഷ", English: "ഇംഗ്ലീഷ്", Hindi: "ഹിന്ദി", Tamil: "തമിഴ്", Malayalam: "മലയാളം", "Time zone": "സമയ മേഖല", "India Standard Time": "ഇന്ത്യൻ സ്റ്റാൻഡേർഡ് സമയം", "Eastern Time": "കിഴക്കൻ സമയം", "Security & privacy": "സുരക്ഷയും സ്വകാര്യതയും", "Active sessions:": "സജീവ സെഷനുകൾ:", "Enhanced privacy preferences": "മെച്ചപ്പെടുത്തിയ സ്വകാര്യത മുൻഗണനകൾ", "Restrict optional data sharing and analytics.": "ഓപ്ഷണൽ ഡാറ്റ പങ്കിടലും വിശകലനവും നിയന്ത്രിക്കുക.", "Log out from all other devices": "മറ്റ് എല്ലാ ഉപകരണങ്ങളിൽ നിന്നും ലോഗ് ഔട്ട് ചെയ്യുക", Saving: "സംരക്ഷിക്കുന്നു…", "Save settings": "ക്രമീകരണങ്ങൾ സംരക്ഷിക്കുക",
  "Track all system activities.": "എല്ലാ സിസ്റ്റം പ്രവർത്തനങ്ങളും നിരീക്ഷിക്കുക.", User: "ഉപയോക്താവ്", Action: "പ്രവർത്തനം", Date: "തീയതി", Time: "സമയം", "Loading live data…": "തത്സമയ ഡാറ്റ ലോഡ് ചെയ്യുന്നു…", "No audit activity is available.": "ഓഡിറ്റ് പ്രവർത്തനങ്ങളൊന്നും ലഭ്യമല്ല."
};
const actions = {
  Tamil: { USER_REGISTERED: "பயனர் பதிவு செய்யப்பட்டார்", DOCTOR_CREATED: "மருத்துவர் உருவாக்கப்பட்டார்", HEALTH_RECORD_ADDED: "உடல்நல பதிவு சேர்க்கப்பட்டது", PRESCRIPTION_ISSUED: "மருந்துச் சீட்டு வழங்கப்பட்டது", APPOINTMENT_BOOKED: "சந்திப்பு பதிவு செய்யப்பட்டது" },
  Hindi: { USER_REGISTERED: "उपयोगकर्ता पंजीकृत हुआ", DOCTOR_CREATED: "डॉक्टर बनाया गया", HEALTH_RECORD_ADDED: "स्वास्थ्य रिकॉर्ड जोड़ा गया", PRESCRIPTION_ISSUED: "प्रिस्क्रिप्शन जारी किया गया", APPOINTMENT_BOOKED: "अपॉइंटमेंट बुक किया गया" },
  Malayalam: { USER_REGISTERED: "ഉപയോക്താവിനെ രജിസ്റ്റർ ചെയ്തു", DOCTOR_CREATED: "ഡോക്ടറെ സൃഷ്ടിച്ചു", HEALTH_RECORD_ADDED: "ആരോഗ്യ രേഖ ചേർത്തു", PRESCRIPTION_ISSUED: "പ്രിസ്ക്രിപ്ഷൻ നൽകി", APPOINTMENT_BOOKED: "അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്തു" }
};
Object.assign(tamil, {
  "Worker Dashboard":"தொழிலாளர் டாஷ்போர்டு", "Migrant Worker":"புலம்பெயர் தொழிலாளர்", "My Profile":"என் சுயவிவரம்", "Health Records":"உடல்நலப் பதிவுகள்", "Prescriptions":"மருந்துச் சீட்டுகள்", "My Prescriptions":"என் மருந்துச் சீட்டுகள்", "Appointments":"சந்திப்புகள்", "Appointment":"சந்திப்பு", "Appointment History":"சந்திப்பு வரலாறு", "Appointment ID":"சந்திப்பு எண்", "QR Code":"QR குறியீடு", "Welcome":"வரவேற்கிறோம்", "View your health records, prescriptions and appointments.":"உங்கள் உடல்நலப் பதிவுகள், மருந்துச் சீட்டுகள் மற்றும் சந்திப்புகளைப் பார்க்கவும்.", "Recent Health Records":"சமீபத்திய உடல்நலப் பதிவுகள்", "Record ID":"பதிவு எண்", "Prescription ID":"மருந்துச் சீட்டு எண்", "Doctor":"மருத்துவர்", "Diagnosis":"நோய் கண்டறிதல்", "Status":"நிலை", "Action":"செயல்", "View":"பார்க்க", "Loading…":"ஏற்றுகிறது…", "No health records found.":"உடல்நலப் பதிவுகள் இல்லை.", "No prescriptions found.":"மருந்துச் சீட்டுகள் இல்லை.", "Book Appointment":"சந்திப்பை பதிவு செய்", "Select Doctor":"மருத்துவரைத் தேர்ந்தெடுக்கவும்", "Choose a doctor":"மருத்துவரைத் தேர்ந்தெடுக்கவும்", "Appointment Date":"சந்திப்பு தேதி", "Appointment Time":"சந்திப்பு நேரம்", "Reason":"காரணம்", "Hospital":"மருத்துவமனை", "Hospital address":"மருத்துவமனை முகவரி", "Download QR Code":"QR குறியீட்டை பதிவிறக்கு", "My Health QR Code":"என் உடல்நல QR குறியீடு", "Scan this QR code to securely access your health records.":"உங்கள் உடல்நலப் பதிவுகளை பாதுகாப்பாக அணுக இந்த QR குறியீட்டை ஸ்கேன் செய்யவும்.", "Settings":"அமைப்புகள்", "Date":"தேதி", "Time":"நேரம்", "Medicine":"மருந்து", "Duration":"கால அளவு"
});
Object.assign(hindi, { "Worker Dashboard":"कार्यकर्ता डैशबोर्ड", "Migrant Worker":"प्रवासी कार्यकर्ता", "My Profile":"मेरी प्रोफ़ाइल", "Health Records":"स्वास्थ्य रिकॉर्ड", "Prescriptions":"पर्चे", "My Prescriptions":"मेरे पर्चे", "Appointments":"अपॉइंटमेंट", "Appointment":"अपॉइंटमेंट", "Appointment History":"अपॉइंटमेंट इतिहास", "Appointment ID":"अपॉइंटमेंट आईडी", "QR Code":"क्यूआर कोड", "Book Appointment":"अपॉइंटमेंट बुक करें", "Select Doctor":"डॉक्टर चुनें", "Choose a doctor":"डॉक्टर चुनें", "Appointment Date":"अपॉइंटमेंट की तारीख", "Appointment Time":"अपॉइंटमेंट का समय", "Reason":"कारण", "Hospital":"अस्पताल", "Hospital address":"अस्पताल का पता", "View":"देखें", "Date":"तारीख", "Time":"समय", "Doctor":"डॉक्टर", "Diagnosis":"निदान", "Status":"स्थिति", "Action":"कार्रवाई", "Record ID":"रिकॉर्ड आईडी", "Prescription ID":"पर्चे की आईडी", "Medicine":"दवा", "Duration":"अवधि", "Welcome":"स्वागत है", "View your health records, prescriptions and appointments.":"अपने स्वास्थ्य रिकॉर्ड, पर्चे और अपॉइंटमेंट देखें।", "Recent Health Records":"हाल के स्वास्थ्य रिकॉर्ड", "Loading…":"लोड हो रहा है…", "No health records found.":"कोई स्वास्थ्य रिकॉर्ड नहीं मिला।", "No prescriptions found.":"कोई पर्चा नहीं मिला।", "My Health QR Code":"मेरा स्वास्थ्य क्यूआर कोड", "Scan this QR code to securely access your health records.":"अपने स्वास्थ्य रिकॉर्ड तक सुरक्षित पहुँच के लिए इस क्यूआर कोड को स्कैन करें।", "Download QR Code":"क्यूआर कोड डाउनलोड करें", "Preparing…":"तैयार हो रहा है…", "Settings":"सेटिंग्स", "Worker Settings":"कार्यकर्ता सेटिंग्स", "(Account Detail - Locked)":"(खाता विवरण - लॉक)", "(Personal Detail)":"(व्यक्तिगत विवरण)" });
Object.assign(malayalam, { "Worker Dashboard":"തൊഴിലാളി ഡാഷ്ബോർഡ്", "Migrant Worker":"പ്രവാസി തൊഴിലാളി", "My Profile":"എന്റെ പ്രൊഫൈൽ", "Health Records":"ആരോഗ്യ രേഖകൾ", "Prescriptions":"കുറിപ്പടികൾ", "My Prescriptions":"എന്റെ കുറിപ്പടികൾ", "Appointment":"അപ്പോയിന്റ്മെന്റ്", "Appointment History":"അപ്പോയിന്റ്മെന്റ് ചരിത്രം", "QR Code":"ക്യുആർ കോഡ്", "Book Appointment":"അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക", "Select Doctor":"ഡോക്ടറെ തിരഞ്ഞെടുക്കുക", "Appointment Date":"അപ്പോയിന്റ്മെന്റ് തീയതി", "Appointment Time":"അപ്പോയിന്റ്മെന്റ് സമയം", "Hospital":"ആശുപത്രി", "Hospital address":"ആശുപത്രി വിലാസം", "View":"കാണുക", "Date":"തീയതി", "Time":"സമയം", "Doctor":"ഡോക്ടർ", "Status":"നില", "Action":"പ്രവർത്തനം" });
Object.assign(tamil, { "Worker Settings":"தொழிலாளர் அமைப்புகள்", "Your registered account details.":"உங்கள் பதிவு செய்யப்பட்ட கணக்கு விவரங்கள்.", "Send a 6-digit verification code to your registered email when you sign in.":"உள்நுழையும்போது உங்கள் பதிவு செய்யப்பட்ட மின்னஞ்சலுக்கு 6 இலக்க சரிபார்ப்புக் குறியீட்டை அனுப்பவும்." });
Object.assign(tamil, {
  "Worker ID":"தொழிலாளர் எண்", "Worker Name":"தொழிலாளர் பெயர்", "Describe the reason for your visit":"உங்கள் சந்திப்புக்கான காரணத்தை விவரிக்கவும்", "Booking…":"பதிவு செய்யப்படுகிறது…", "View all your previous appointments.":"உங்கள் முந்தைய சந்திப்புகள் அனைத்தையும் பார்க்கவும்.", "View all your medical history.":"உங்கள் முழு மருத்துவ வரலாற்றையும் பார்க்கவும்.", "View all prescribed medicines.":"பரிந்துரைக்கப்பட்ட அனைத்து மருந்துகளையும் பார்க்கவும்.",
  "Full Name": "முழு பெயர்", "Email Address": "மின்னஞ்சல் முகவரி", "Risk Level": "ஆபத்து நிலை", "Age": "வயது", "Phone Number": "தொலைபேசி எண்", "Address / Health History": "முகவரி / உடல்நல வரலாறு", "Edit Personal Details (Age, Phone, Address)": "தனிப்பட்ட விவரங்களை திருத்து (வயது, தொலைபேசி, முகவரி)", "Cancel": "ரத்து செய்", "Save Changes": "மாற்றங்களைச் சேமி", "Updating DB…": "தரவுத்தளம் புதுப்பிக்கப்படுகிறது…", "(Account Detail - Locked)": "(கணக்கு விவரம் - மாற்ற முடியாது)", "(Personal Detail)": "(தனிப்பட்ட விவரம்)"
});
Object.assign(hindi, {
  "Worker ID":"कार्यकर्ता आईडी", "Worker Name":"कार्यकर्ता का नाम", "Describe the reason for your visit":"अपनी यात्रा का कारण बताएं", "Booking…":"बुकिंग हो रही है…", "View all your previous appointments.":"अपने सभी पिछले अपॉइंटमेंट देखें।", "View all your medical history.":"अपना पूरा चिकित्सा इतिहास देखें।", "View all prescribed medicines.":"सभी निर्धारित दवाएं देखें।",
  "Full Name": "पूरा नाम", "Email Address": "ईमेल पता", "Risk Level": "जोखिम स्तर", "Age": "आयु", "Phone Number": "फ़ोन नंबर", "Address / Health History": "पता / स्वास्थ्य इतिहास", "Edit Personal Details (Age, Phone, Address)": "व्यक्तिगत विवरण संपादित करें (आयु, फोन, पता)", "Cancel": "रद्द करें", "Save Changes": "परिवर्तन सहेजें", "Updating DB…": "डेटाबेस अपडेट हो रहा है…"
});
Object.assign(malayalam, {
  "Worker ID":"തൊഴിലാളി ഐഡി", "Worker Name":"തൊഴിലാളിയുടെ പേര്", "Describe the reason for your visit":"നിങ്ങളുടെ സന്ദർശനത്തിനുള്ള കാരണം വിശദീകരിക്കുക", "Booking…":"ബുക്കിംഗ്…", "View all your previous appointments.":"നിങ്ങളുടെ മുൻകാല അപ്പോയിന്റ്മെന്റുകളെല്ലാം കാണുക.", "View all your medical history.":"നിങ്ങളുടെ മുഴുവൻ മെഡിക്കൽ ചരിത്രവും കാണുക.", "View all prescribed medicines.":"നിർദ്ദേശിക്കപ്പെട്ട എല്ലാ മരുന്നുകളും കാണുക.",
  "Full Name": "മുഴുവൻ പേര്", "Email Address": "ഇമെയിൽ വിലാസം", "Risk Level": "അപകടസാധ്യത", "Age": "വയസ്സ്", "Phone Number": "ഫോൺ നമ്പർ", "Address / Health History": "വിലാസം / ആരോഗ്യ ചരിത്രം", "Edit Personal Details (Age, Phone, Address)": "വ്യക്തിഗത വിവരങ്ങൾ എഡിറ്റ് ചെയ്യുക (വയസ്സ്, ഫോൺ, വിലാസം)", "Cancel": "റദ്ദാക്കുക", "Save Changes": "മാറ്റങ്ങൾ സംരക്ഷിക്കുക", "Updating DB…": "ഡാറ്റാബേസ് അപ്‌ഡേറ്റ് ചെയ്യുന്നു…"
});
const dictionaries = { Tamil: tamil, Hindi: hindi, Malayalam: malayalam };
const LanguageContext = createContext({ language: "English", setLanguage: () => {}, t: (value) => value, translateAction: (value) => value });
export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem(languageKey) || "English");
  const setLanguage = useCallback((value) => { setLanguageState(value); localStorage.setItem(languageKey, value); }, []);
  useEffect(() => { document.documentElement.lang = ({ Tamil: "ta", Hindi: "hi", Malayalam: "ml" })[language] || "en"; }, [language]);
  const t = (value) => dictionaries[language]?.[value] || value;
  const translateAction = (value) => actions[language]?.[value] || ({ USER_REGISTERED: "User Registered", DOCTOR_CREATED: "Created Doctor", HEALTH_RECORD_ADDED: "Added Health Record", PRESCRIPTION_ISSUED: "Issued Prescription", APPOINTMENT_BOOKED: "Booked Appointment" }[value] || value.replaceAll("_", " "));
  return <LanguageContext.Provider value={{ language, setLanguage, t, translateAction }}>{children}</LanguageContext.Provider>;
}
export const useLanguage = () => useContext(LanguageContext);
