import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import axios from "axios";
import "./DoctorVerification.css";

const blank = { fullName:"", phone:"", medicalRegistrationNumber:"", medicalCouncil:"", registrationDate:"", registrationStatus:"Active", medicalDegree:"", specialization:"", hospital:"", hospitalAddress:"", experience:"", password:"", confirmPassword:"" };
const toData = (file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); });

export default function DoctorVerification() {
  const [params] = useSearchParams(); const token = params.get("token") || "";
  const [form, setForm] = useState(blank); const [certificate, setCertificate] = useState(null); const [governmentId, setGovernmentId] = useState(null); const [state, setState] = useState({ loading:true, error:"", done:"", email:"" }); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (!token) { setState({ loading:false, error:"Verification link is missing.", done:"", email:"" }); return; } axios.get("/api/doctor-applications/form", { params:{ token } }).then(({data}) => { setForm((current) => ({...current, fullName:data.fullName || ""})); setState({loading:false,error:"",done:"",email:data.email}); }).catch((error) => setState({loading:false,error:error.response?.data?.message || "Unable to open this verification form.",done:"",email:""})); }, [token]);
  const change = (event) => setForm((current) => ({ ...current, [event.target.name]:event.target.value }));
  const choose = (setter) => (event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) { setState((current) => ({...current,error:"Each document must be 5 MB or smaller."})); event.target.value=""; return; } setter(file); };
  const submit = async (event) => { event.preventDefault(); if (form.password !== form.confirmPassword) { setState((current) => ({...current,error:"Passwords do not match."})); return; } if (!certificate || !governmentId) { setState((current) => ({...current,error:"Upload both the medical registration certificate and government ID."})); return; } setSubmitting(true); setState((current) => ({...current,error:""})); try { const [certificateData, governmentIdData] = await Promise.all([toData(certificate), toData(governmentId)]); await axios.post("/api/doctor-applications/submit", { ...form, token, registrationCertificateData:certificateData, registrationCertificateName:certificate.name, registrationCertificateMimeType:certificate.type, governmentIdData, governmentIdName:governmentId.name, governmentIdMimeType:governmentId.type }); setState((current) => ({...current,done:"Your verification form has been submitted. HealthSync Administration will email you after review."})); } catch (error) { setState((current) => ({...current,error:error.response?.data?.message || "Unable to submit your verification form."})); } finally { setSubmitting(false); } };
  if (state.loading) return <main className="doctor-verification-page"><section className="verification-card"><p>Opening secure verification form…</p></section></main>;
  if (state.error && !state.email) return <main className="doctor-verification-page"><section className="verification-card"><h1>Doctor verification</h1><p className="verification-error">{state.error}</p></section></main>;
  if (state.done) return <main className="doctor-verification-page"><section className="verification-card"><h1>Form submitted</h1><p className="verification-success">{state.done}</p></section></main>;
  return <main className="doctor-verification-page"><section className="verification-card"><span className="verification-brand">HealthSync</span><h1>Doctor verification form</h1><p className="verification-subtitle">Complete the form for <strong>{state.email}</strong>. Your account will be enabled after administrator approval.</p>{state.error && <p className="verification-error">{state.error}</p>}<form onSubmit={submit} className="verification-form"><Field label="Full name" name="fullName" value={form.fullName} onChange={change}/><Field label="Phone number" name="phone" value={form.phone} onChange={change}/><Field label="Medical Registration Number" name="medicalRegistrationNumber" value={form.medicalRegistrationNumber} onChange={change}/><Field label="Medical Council / Registering Authority" name="medicalCouncil" value={form.medicalCouncil} onChange={change}/><Field label="Registration Date" type="date" name="registrationDate" value={form.registrationDate} onChange={change}/><Field label="Registration Status" name="registrationStatus" value={form.registrationStatus} onChange={change}/><Field label="Medical Degree" name="medicalDegree" value={form.medicalDegree} onChange={change} placeholder="MBBS, MD, MS..."/><Field label="Specialization" name="specialization" value={form.specialization} onChange={change}/><Field label="Hospital / Institution" name="hospital" value={form.hospital} onChange={change}/><Field label="Experience" name="experience" value={form.experience} onChange={change} placeholder="e.g. 8 years"/><label className="verification-full">Hospital / Institution Address<input required name="hospitalAddress" value={form.hospitalAddress} onChange={change}/></label><Upload label="Medical Registration Certificate (PDF/Image)" file={certificate} onChange={choose(setCertificate)}/><Upload label="Government ID (PDF/Image)" file={governmentId} onChange={choose(setGovernmentId)}/><Field label="Create password" type="password" name="password" value={form.password} onChange={change}/><Field label="Confirm password" type="password" name="confirmPassword" value={form.confirmPassword} onChange={change}/><button disabled={submitting}>{submitting ? "Submitting…" : "Submit for verification"}</button></form></section></main>;
}
function Field({label, type="text", ...props}) { return <label>{label}<input required type={type} {...props}/></label>; }
function Upload({label,file,onChange}) { return <label>{label}<input required type="file" accept="application/pdf,image/*" onChange={onChange}/><small>{file ? file.name : "PDF or image, up to 5 MB"}</small></label>; }
