import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import AdminService from "../../services/AdminService";
import { notify } from "../../components/ToastProvider";
import "./DoctorVerifications.css";
const dateTime = (v) => v ? new Date(v).toLocaleString() : "—";

export default function DoctorVerifications() {
  const navigate = useNavigate();
  const [applications, setApplications] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [viewing, setViewing] = useState(null);
  const [invite, setInvite] = useState({ fullName: "", email: "" });
  const load = useCallback(async () => { setLoading(true); try { const { data } = await AdminService.getDoctorApplications(); setApplications(Array.isArray(data) ? data : []); } catch (e) { notify.error(e.response?.data?.message || "Unable to load doctor verification requests."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const send = async (e, app) => { e?.preventDefault(); setBusy(true); try { await AdminService.inviteDoctorApplication(app ? { fullName: app.fullName || "", email: app.email } : invite); notify.success("Verification form invitation sent to the doctor."); setInvite({ fullName: "", email: "" }); load(); } catch (x) { notify.error(x.response?.data?.message || "Unable to send the invitation."); } finally { setBusy(false); } };
  const approve = async (id) => { if (!window.confirm("Approve this application? The doctor will receive an approval email.")) return; setBusy(true); try { notify.success((await AdminService.approveDoctorApplication(id)).data.message); load(); } catch (x) { notify.error(x.response?.data?.message || "Unable to approve this application."); } finally { setBusy(false); } };
  const reject = async (id) => { const reason = window.prompt("Enter the rejection reason that will be emailed to the doctor:"); if (!reason?.trim()) return; setBusy(true); try { notify.success((await AdminService.rejectDoctorApplication(id, reason.trim())).data.message); load(); } catch (x) { notify.error(x.response?.data?.message || "Unable to reject this application."); } finally { setBusy(false); } };
  const cancel = async (a) => { if (!window.confirm(`Cancel the invitation for ${a.email}?`)) return; setBusy(true); try { notify.success((await AdminService.cancelDoctorApplication(a.id)).data.message); load(); } catch (x) { notify.error(x.response?.data?.message || "Unable to cancel this invitation."); } finally { setBusy(false); } };
  const doc = async (id, type) => { try { const { data } = await AdminService.getDoctorApplicationDocument(id, type); window.open(URL.createObjectURL(data), "_blank", "noopener,noreferrer"); } catch { notify.error("Unable to open this document."); } };
  const actions = (a) => a.status === "INVITED" ? <><button disabled={busy} onClick={() => send(null, a)}>Resend</button><button className="cancel" disabled={busy} onClick={() => cancel(a)}>Cancel</button></> : a.status === "SUBMITTED" ? <><button onClick={() => doc(a.id, "certificate")}>Certificate</button><button onClick={() => doc(a.id, "government-id")}>Government ID</button><button className="approve" disabled={busy} onClick={() => approve(a.id)}>Approve</button><button className="reject" disabled={busy} onClick={() => reject(a.id)}>Reject</button></> : a.status === "APPROVED" ? <button className="approve" onClick={() => setViewing(a)}>View</button> : a.status === "ACCOUNT_CREATED" ? "Account created" : "Rejection sent";
  return <div className="doctor-verifications"><div className="pageHeader"><h2>Doctor Verification</h2><p>Invite doctors, review professional credentials, and approve or reject applications.</p></div><section className="verification-invite"><h3>Invite a doctor</h3><p>The doctor receives a secure email link to complete their professional verification form.</p><form onSubmit={send}><input placeholder="Doctor name (optional)" value={invite.fullName} onChange={(e) => setInvite({ ...invite, fullName: e.target.value })}/><input required type="email" placeholder="Doctor email" value={invite.email} onChange={(e) => setInvite({ ...invite, email: e.target.value })}/><button disabled={busy}>{busy ? "Sending…" : "Send verification form"}</button></form></section><section className="verification-table"><div className="verification-table-heading"><h3>Applications</h3><button onClick={load} disabled={loading}>Refresh</button></div><table><thead><tr><th>Doctor</th><th>Registration no.</th><th>Credentials</th><th>Hospital</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan="6">Loading applications…</td></tr> : applications.length ? applications.map((a) => <tr key={a.id}><td><strong>{a.fullName || "Invitation pending"}</strong><small>{a.email}</small></td><td>{a.status === "INVITED" ? "Not submitted yet" : a.medicalRegistrationNumber || "—"}<small>{a.medicalCouncil || ""}</small></td><td>{a.status === "INVITED" ? "Not submitted yet" : a.medicalDegree || "—"}<small>{a.specialization || ""}</small></td><td>{a.status === "INVITED" ? "Not submitted yet" : a.hospital || "—"}<small>{a.hospitalAddress || ""}</small></td><td><span className={`verification-status ${String(a.status).toLowerCase()}`}>{a.status}</span>{a.status === "INVITED" && <small>Expires: {dateTime(a.expiresAt)}</small>}{a.rejectionReason && <small>{a.rejectionReason}</small>}</td><td className="verification-actions">{actions(a)}</td></tr>) : <tr><td colSpan="6">No doctor verification invitations yet.</td></tr>}</tbody></table></section>{viewing && <Details app={viewing} close={() => setViewing(null)} onAdd={() => navigate("/admin/create-doctor", { state: { approvedApplication: viewing } })} />}</div>;
}
function Details({ app, close, onAdd }) { const rows = [["Full name",app.fullName],["Email",app.email],["Phone",app.phone],["Medical registration number",app.medicalRegistrationNumber],["Medical council",app.medicalCouncil],["Medical degree",app.medicalDegree],["Specialization",app.specialization],["Hospital / institution",app.hospital],["Hospital address",app.hospitalAddress],["Experience",app.experience]]; return <div className="application-view-backdrop" onMouseDown={close}><section className="application-view" onMouseDown={(e)=>e.stopPropagation()}><header><h3>Doctor submitted details</h3><button onClick={close}>×</button></header><div>{rows.map(([k,v])=><p key={k}><strong>{k}</strong><span>{v || "—"}</span></p>)}</div><small>The doctor's submitted password is protected and will be reused when the account is created.</small><footer><button className="application-add" onClick={onAdd}>Add doctor using these details</button><button onClick={close}>Close</button></footer></section></div>; }
